name: Check build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential libx11-dev libxft-dev libxext-dev
    - name: make
      run: make
    - name: make clean install
      run: make clean install
